package logger

import "fmt"

// A Tag is an optional int value. Tag(s) will not render with a zero value, a
// special case. Tags offer a way of adding types to log entries without making
// types a first-class concern. String messages are still the focus, but string
// messages generated in similar parts of a program can be differentiated using
// ints (perhaps generated by iota) and found in very large log files using
// grep. A single message can have more than one. Think of these like Gmail's
// labels but on log entries.
type Tag int

// String fulfills the Stringer interface.
func (t Tag) String() string {
	return fmt.Sprintf("t%d", t)
}
